import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from "./provider";
import Navbar from './component/header';
import TopBar from './component/topbar';

// const inter = Inter({ subsets: ['Outfit'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopBar />
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}